import os
import sys
from typing import List


def get_project_root() -> str:
    """Return the project root directory (parent of core/)."""
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_base_dir() -> str:
    """Return the directory used as runtime base (handles PyInstaller onefile)."""
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return get_project_root()


def _candidate_config_names() -> List[str]:
    """Only YAML configs are supported now."""
    return ["config.yml", "config.yaml"]


def _candidate_user_config_names() -> List[str]:
    """User config file names (generated by setup wizard)."""
    return ["user_config.yml", "user_config.yaml"]


def get_bundled_config_paths() -> list[str]:
    """
    Paths for built-in default config (inside the bundle or next to the script).
    Only YAML configs are supported now.
    """
    bundle_dir = getattr(sys, "_MEIPASS", None)  # PyInstaller onefile temp dir
    base = bundle_dir or get_project_root()
    return [os.path.join(base, name) for name in _candidate_config_names()]


def get_external_config_paths() -> list[str]:
    """
    Paths for user-override config (next to the executable).
    Includes both standard config.yml overrides and user_config.yml from wizard.
    """
    base_dir = get_base_dir()
    paths = [os.path.join(base_dir, name) for name in _candidate_config_names()]
    # User config from wizard (higher priority)
    paths.extend([os.path.join(base_dir, name) for name in _candidate_user_config_names()])
    return paths
